"""Add email column to users table

Revision ID: 9e8553f115f5
Revises: a787698e14f0
Create Date: 2025-11-01 19:23:59.807562

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9e8553f115f5'
down_revision = 'a787698e14f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collector_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=False),
    sa.Column('assignment_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('collector_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=15), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('creation_date', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['collector_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('extra_days', sa.Integer(), nullable=False),
    sa.Column('extra_interest_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('penalty_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('applied_date', sa.DateTime(), nullable=True),
    sa.Column('applied_by', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['applied_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('interest_rate', sa.Numeric(precision=5, scale=4), nullable=False))
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('expected_end_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('actual_end_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('total_days_paid', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('loans_customer_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['admin_id'], ['id'])
        batch_op.create_foreign_key(None, 'customers', ['customer_id'], ['id'])
        batch_op.drop_column('interest')
        batch_op.drop_column('original_total')
        batch_op.drop_column('original_end_date')
        batch_op.drop_column('state')
        batch_op.drop_column('current_end_date')
        batch_op.drop_column('extra_days')
        batch_op.drop_column('current_total')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('days_covered', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.drop_column('monto_pagado')
        batch_op.drop_column('fecha_pago')
        batch_op.drop_column('observaciones')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.create_unique_constraint(None, ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('email')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('observaciones', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fecha_pago', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('monto_pagado', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('notes')
        batch_op.drop_column('days_covered')
        batch_op.drop_column('payment_date')
        batch_op.drop_column('amount')

    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('extra_days', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('current_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('original_end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('original_total', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('interest', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('loans_customer_id_fkey'), 'users', ['customer_id'], ['id'])
        batch_op.drop_column('total_days_paid')
        batch_op.drop_column('status')
        batch_op.drop_column('actual_end_date')
        batch_op.drop_column('expected_end_date')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('interest_rate')
        batch_op.drop_column('admin_id')

    op.drop_table('loan_penalties')
    op.drop_table('customers')
    op.drop_table('collector_assignments')
    # ### end Alembic commands ###
